# Generated by Django 4.0 on 2022-01-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangsaapp', '0002_cat_adoption_dog_adoption_delete_catadoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_adoption',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dog_adoption',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cat_adoption',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dog_adoption',
            name='description',
            field=models.TextField(),
        ),
    ]
