# Generated by Django 4.0 on 2022-01-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jangsaapp', '0003_cat_adoption_created_dog_adoption_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat_adoption',
            new_name='cat',
        ),
        migrations.RenameModel(
            old_name='dog_adoption',
            new_name='dog',
        ),
    ]
