# Generated by Django 4.0 on 2022-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangsaapp', '0004_rename_cat_adoption_cat_rename_dog_adoption_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='cat'),
        ),
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dog'),
        ),
    ]
