# Generated by Django 4.0 on 2022-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangsaapp', '0005_cat_image_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='cat'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(upload_to='dog'),
        ),
    ]
