# Generated by Django 4.0 on 2022-01-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangsaapp', '0006_alter_cat_image_alter_dog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JangsaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
