# Generated by Django 4.0 on 2022-01-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangsaapp', '0007_jangsauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jangsauser',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
