# Generated by Django 4.0 on 2022-01-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangsaapp', '0008_alter_cat_name_alter_jangsauser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='jangsauser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jangsauser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jangsauser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jangsauser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jangsauser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jangsauser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='jangsauser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
